import FiniteQuerySandbox.DAG.Ancestry

open Finset

namespace FiniteQuerySandbox

noncomputable section

namespace DAG

/-- Two distinct vertices with a common child in the directed graph. -/
def coParents (G : DAG) (u v : ℕ) : Prop :=
  ∃ w : ℕ, G.HasEdge u w ∧ G.HasEdge v w ∧ u ≠ v

/--
The moral graph of the ancestral subgraph generated by `S`: forget edge
directions and connect co-parents.
-/
def moralGraph (G : DAG) (S : Finset ℕ) : SimpleGraph ℕ where
  Adj u v :=
    let G' := G.ancestralSubgraph S
    u ∈ G'.nodes ∧ v ∈ G'.nodes ∧ u ≠ v ∧
      (G'.HasEdge u v ∨ G'.HasEdge v u ∨ G'.coParents u v)
  symm := by
    intro u v h
    dsimp at h ⊢
    rcases h with ⟨hu, hv, hne, hedge | hedge | hcop⟩
    · exact ⟨hv, hu, Ne.symm hne, Or.inr (Or.inl hedge)⟩
    · exact ⟨hv, hu, Ne.symm hne, Or.inl hedge⟩
    · rcases hcop with ⟨w, huw, hvw, huv⟩
      exact ⟨hv, hu, Ne.symm hne, Or.inr (Or.inr ⟨w, hvw, huw, Ne.symm huv⟩)⟩
  loopless := by
    constructor
    intro u h
    exact h.2.2.1 rfl

end DAG

end

end FiniteQuerySandbox
