import Mathlib

open Finset

namespace FiniteQuerySandbox

noncomputable section

/-!
# DAG Parser

This module provides the graph-theoretic side of the DAG automation layer.  It
intentionally keeps the first pass finite and concrete: nodes are natural
numbers, edges are a finite set of ordered pairs, and acyclicity is recorded as
well-foundedness of the edge relation.
-/

/-- A finite directed acyclic graph over natural-number node labels. -/
structure DAG where
  nodes : Finset ℕ
  edges : Finset (ℕ × ℕ)
  edges_subset : ∀ {u v : ℕ}, (u, v) ∈ edges → u ∈ nodes ∧ v ∈ nodes
  acyclic : WellFounded fun u v => (u, v) ∈ edges

namespace DAG

/-- Directed edge predicate. -/
def HasEdge (G : DAG) (u v : ℕ) : Prop :=
  (u, v) ∈ G.edges

/--
Build a DAG from a rank function that strictly increases along every edge.
This is a convenient way to construct examples without proving
well-foundedness directly.
-/
def ofRank (nodes : Finset ℕ) (edges : Finset (ℕ × ℕ)) (rank : ℕ → ℕ)
    (edges_subset : ∀ {u v : ℕ}, (u, v) ∈ edges → u ∈ nodes ∧ v ∈ nodes)
    (rank_increases : ∀ {u v : ℕ}, (u, v) ∈ edges → rank u < rank v) : DAG where
  nodes := nodes
  edges := edges
  edges_subset := edges_subset
  acyclic :=
    (InvImage.wf rank wellFounded_lt).mono fun _ _ h => rank_increases h

/-- A rank is compatible with the DAG if it strictly increases along edges. -/
def RespectsTopologicalRank (G : DAG) (rank : ℕ → ℕ) : Prop :=
  ∀ {u v : ℕ}, G.HasEdge u v → rank u < rank v

end DAG

/-- Directed reachability, including the zero-length path. -/
def Reachable (G : DAG) (u v : ℕ) : Prop :=
  Relation.ReflTransGen (fun a b => G.HasEdge a b) u v

lemma not_transGen_self_of_wellFounded {α : Type} {r : α → α → Prop}
    (h : WellFounded r) (a : α) :
    ¬ Relation.TransGen r a a := by
  induction a using h.induction with
  | h x ih =>
      intro hcycle
      rcases Relation.TransGen.tail'_iff.mp hcycle with ⟨y, hxy, hyx⟩
      rcases Relation.reflTransGen_iff_eq_or_transGen.mp hxy with h_eq | htrans
      · subst y
        exact h.irrefl.irrefl x hyx
      · exact ih y hyx (Relation.TransGen.head hyx htrans)

/-- Incoming neighbors of `v`. -/
def parents (G : DAG) (v : ℕ) : Finset ℕ :=
  (G.edges.filter fun e => e.2 = v).image Prod.fst

/-- Outgoing neighbors of `v`. -/
def children (G : DAG) (v : ℕ) : Finset ℕ :=
  (G.edges.filter fun e => e.1 = v).image Prod.snd

/-- A leaf node is a graph node with no outgoing edges. -/
def IsLeaf (G : DAG) (v : ℕ) : Prop :=
  v ∈ G.nodes ∧ children G v = ∅

/-- Every nonempty finite DAG has at least one leaf node. -/
lemma exists_leaf_of_nonempty (G : DAG) (h_nodes : G.nodes.Nonempty) :
    ∃ v : ℕ, IsLeaf G v := by
  classical
  let Node := {v : ℕ // v ∈ G.nodes}
  letI : Fintype Node := Finset.Subtype.fintype G.nodes
  letI : LE Node := ⟨fun a b => Reachable G a.1 b.1⟩
  letI : IsTrans Node (· ≤ ·) := ⟨by
    intro a b c hab hbc
    exact Relation.ReflTransGen.trans hab hbc⟩
  have h_univ : (Finset.univ : Finset Node).Nonempty := by
    rcases h_nodes with ⟨v, hv⟩
    exact ⟨⟨v, hv⟩, Finset.mem_univ _⟩
  obtain ⟨m, hmax⟩ := (Finset.univ : Finset Node).exists_maximal h_univ
  refine ⟨m.1, m.2, ?_⟩
  apply eq_empty_iff_forall_notMem.mpr
  intro w hw
  rcases Finset.mem_image.mp hw with ⟨e, he_filter, hwe⟩
  have he_edges : e ∈ G.edges := (Finset.mem_filter.mp he_filter).1
  have he_src : e.1 = m.1 := (Finset.mem_filter.mp he_filter).2
  rcases e with ⟨u, z⟩
  simp at he_src hwe
  subst u
  subst w
  have h_edge : G.HasEdge m.1 z := by
    simpa [DAG.HasEdge] using he_edges
  let child : Node := ⟨z, (G.edges_subset h_edge).2⟩
  have h_forward : m ≤ child := Relation.ReflTransGen.single h_edge
  have h_back : child ≤ m := hmax.2 (Finset.mem_univ child) h_forward
  have hcycle : Relation.TransGen (fun a b => G.HasEdge a b) m.1 m.1 :=
    Relation.TransGen.head' h_edge h_back
  exact (not_transGen_self_of_wellFounded G.acyclic m.1) hcycle

/-- Nodes reachable from `v`, excluding `v` itself. -/
def descendants (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun w => w ≠ v ∧ Reachable G v w

/-- Nodes that can reach `v`, excluding `v` itself. -/
def ancestors (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun u => u ≠ v ∧ Reachable G u v

/-- Nodes that are not descendants of `v`, excluding `v`. -/
def nonDescendants (G : DAG) (v : ℕ) : Finset ℕ :=
  G.nodes \ ({v} ∪ descendants G v)

namespace DAG

/-- Ancestors of a node, including the node itself when it belongs to `G.nodes`. -/
def ancestors (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun u => Reachable G u v

/-- Nodes in the ancestral subgraph generated by a node set. -/
def ancestralSubgraphNodes (G : DAG) (S : Finset ℕ) : Finset ℕ :=
  S.biUnion fun v => G.ancestors v

/-- The directed subgraph induced by the ancestral node set of `S`. -/
def ancestralSubgraph (G : DAG) (S : Finset ℕ) : DAG where
  nodes := G.ancestralSubgraphNodes S
  edges := G.edges.filter fun e =>
    e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S
  edges_subset := by
    intro u v h
    exact (Finset.mem_filter.mp h).2
  acyclic :=
    G.acyclic.mono fun _ _ h => (Finset.mem_filter.mp h).1

/-- Delete a vertex and all incident directed edges. -/
def deleteLeaf (G : DAG) (v : ℕ) : DAG where
  nodes := G.nodes.erase v
  edges := G.edges.filter fun e => e.1 ≠ v ∧ e.2 ≠ v
  edges_subset := by
    intro u w h
    rcases Finset.mem_filter.mp h with ⟨hedge, hu_ne, hw_ne⟩
    exact ⟨Finset.mem_erase.mpr ⟨hu_ne, (G.edges_subset hedge).1⟩,
      Finset.mem_erase.mpr ⟨hw_ne, (G.edges_subset hedge).2⟩⟩
  acyclic :=
    G.acyclic.mono fun _ _ h => (Finset.mem_filter.mp h).1

lemma deleteLeaf_card_lt {G : DAG} {v : ℕ} (hv : v ∈ G.nodes) :
    (G.deleteLeaf v).nodes.card < G.nodes.card := by
  simpa [DAG.deleteLeaf] using Finset.card_erase_lt_of_mem hv

/-- Two distinct vertices with a common child in the directed graph. -/
def coParents (G : DAG) (u v : ℕ) : Prop :=
  ∃ w : ℕ, G.HasEdge u w ∧ G.HasEdge v w ∧ u ≠ v

/--
The moral graph of the ancestral subgraph generated by `S`: forget edge
directions and connect co-parents.
-/
def moralGraph (G : DAG) (S : Finset ℕ) : SimpleGraph ℕ where
  Adj u v :=
    let G' := G.ancestralSubgraph S
    u ∈ G'.nodes ∧ v ∈ G'.nodes ∧ u ≠ v ∧
      (G'.HasEdge u v ∨ G'.HasEdge v u ∨ G'.coParents u v)
  symm := by
    intro u v h
    dsimp at h ⊢
    rcases h with ⟨hu, hv, hne, hedge | hedge | hcop⟩
    · exact ⟨hv, hu, Ne.symm hne, Or.inr (Or.inl hedge)⟩
    · exact ⟨hv, hu, Ne.symm hne, Or.inl hedge⟩
    · rcases hcop with ⟨w, huw, hvw, huv⟩
      exact ⟨hv, hu, Ne.symm hne, Or.inr (Or.inr ⟨w, hvw, huw, Ne.symm huv⟩)⟩
  loopless := by
    constructor
    intro u h
    exact h.2.2.1 rfl

/-- Nodes retained after moralization and deletion of the conditioning set. -/
def dSeparationGraphNodes (G : DAG) (X Y Z : Finset ℕ) : Finset ℕ :=
  G.ancestralSubgraphNodes (X ∪ Y ∪ Z) \ Z

/-- Moralized ancestral graph with the conditioning set `Z` removed. -/
def dSeparationGraph (G : DAG) (X Y Z : Finset ℕ) : SimpleGraph ℕ where
  Adj u v :=
    u ∈ G.dSeparationGraphNodes X Y Z ∧
      v ∈ G.dSeparationGraphNodes X Y Z ∧
      (G.moralGraph (X ∪ Y ∪ Z)).Adj u v
  symm := by
    intro u v h
    exact ⟨h.2.1, h.1, (G.moralGraph (X ∪ Y ∪ Z)).symm h.2.2⟩
  loopless := by
    constructor
    intro u h
    exact (G.moralGraph (X ∪ Y ∪ Z)).loopless.irrefl u h.2.2

/--
d-separation by the ancestral-subgraph/moralization/deletion criterion:
after moralizing ancestors of `X ∪ Y ∪ Z` and deleting `Z`, no `X` node is
connected to any `Y` node.
-/
def dSeparated (G : DAG) (X Y Z : Finset ℕ) : Prop :=
  ∀ x, x ∈ X → ∀ y, y ∈ Y → ¬(G.dSeparationGraph X Y Z).Reachable x y

end DAG

/-- Undirected adjacency induced by the directed edge set. -/
def Adjacent (G : DAG) (u v : ℕ) : Prop :=
  G.HasEdge u v ∨ G.HasEdge v u

/-- Consecutive entries in a list satisfy a relation. -/
def Consecutive (R : ℕ → ℕ → Prop) : List ℕ → Prop
  | [] => True
  | [_] => True
  | a :: b :: rest => R a b ∧ Consecutive R (b :: rest)

/-- A list contains the consecutive triple `a, b, c`. -/
def HasTriple (xs : List ℕ) (a b c : ℕ) : Prop :=
  ∃ pre post : List ℕ, xs = pre ++ a :: b :: c :: post

/-- A trail is a finite undirected walk in the underlying graph. -/
inductive Trail (G : DAG) : ℕ → ℕ → Type where
  | nil (v : ℕ) : Trail G v v
  | forward {u w v : ℕ} (h : G.HasEdge u w) (tail : Trail G w v) : Trail G u v
  | backward {u w v : ℕ} (h : G.HasEdge w u) (tail : Trail G w v) : Trail G u v

namespace Trail

/-- Vertices visited by a trail, in order. -/
def toList {G : DAG} : {u v : ℕ} → Trail G u v → List ℕ
  | _, _, nil v => [v]
  | u, _, forward (u := _) (w := _) (v := _) _ tail => u :: toList tail
  | u, _, backward (u := _) (w := _) (v := _) _ tail => u :: toList tail

/-- Vertices visited by a trail as a finite set. -/
def nodes {G : DAG} {u v : ℕ} (t : Trail G u v) : Finset ℕ :=
  t.toList.toFinset

@[simp]
lemma mem_nodes {G : DAG} {u v a : ℕ} {t : Trail G u v} :
    a ∈ t.nodes ↔ a ∈ t.toList := by
  simp [nodes]

/-- If the start of a trail is a graph node, then so is its endpoint. -/
lemma target_mem_graph_nodes_of_source_mem {G : DAG} {u v : ℕ}
    (t : Trail G u v) (hu : u ∈ G.nodes) :
    v ∈ G.nodes := by
  induction t with
  | nil _ =>
      exact hu
  | forward h tail ih =>
      exact ih (G.edges_subset h).2
  | backward h tail ih =>
      exact ih (G.edges_subset h).1

end Trail

/-- A middle vertex is a collider on the local triple `a-b-c`. -/
def TripleCollider (G : DAG) (a b c : ℕ) : Prop :=
  G.HasEdge a b ∧ G.HasEdge c b

/--
The local triple is blocked by the conditioning set.  Non-colliders are blocked
when conditioned on directly; colliders are blocked unless the collider or one
of its descendants is conditioned on.
-/
def TripleBlocked (G : DAG) (Z : Finset ℕ) (a b c : ℕ) : Prop :=
  (¬ TripleCollider G a b c ∧ b ∈ Z) ∨
    (TripleCollider G a b c ∧ Disjoint ({b} ∪ descendants G b) Z)

/--
Direction of an edge as seen from the vertex being entered.  `into` means the
edge arrow points into the current vertex; `outOf` means the arrow points out of
the current vertex toward the previous one.
-/
inductive TrailDir where
  | into
  | outOf
  deriving DecidableEq

namespace TrailDir

/-- The directed edge orientation by which a trail enters `curr` from `prev`. -/
def edgeIntoCurrent (G : DAG) (prev curr : ℕ) : TrailDir → Prop
  | into => G.HasEdge prev curr
  | outOf => G.HasEdge curr prev

/--
The local triple is a collider exactly when the trail enters the middle vertex
along an incoming arrow and leaves along another arrow into the middle vertex.
-/
def colliderAtCurrent (arrival departure : TrailDir) : Prop :=
  arrival = into ∧ departure = outOf

end TrailDir

/-- Direction-only version of `TripleBlocked`, used by the Bayes-ball scaffold. -/
def DirectionalTripleBlocked (G : DAG) (Z : Finset ℕ) (b : ℕ)
    (arrival departure : TrailDir) : Prop :=
  (¬ TrailDir.colliderAtCurrent arrival departure ∧ b ∈ Z) ∨
    (TrailDir.colliderAtCurrent arrival departure ∧
      Disjoint ({b} ∪ descendants G b) Z)

lemma directionalTripleBlocked_iff_tripleBlocked {G : DAG} {Z : Finset ℕ}
    {a b c : ℕ} {arrival departure : TrailDir}
    (hab : TrailDir.edgeIntoCurrent G a b arrival)
    (hbc : TrailDir.edgeIntoCurrent G b c departure) :
    DirectionalTripleBlocked G Z b arrival departure ↔ TripleBlocked G Z a b c := by
  cases arrival <;> cases departure
  · simp [TrailDir.edgeIntoCurrent] at hab hbc
    have hnot_cb : ¬ G.HasEdge c b := by
      intro hrev
      have hcycle : Relation.TransGen (fun u v => G.HasEdge u v) b b :=
        Relation.TransGen.head hbc (Relation.TransGen.single hrev)
      exact (not_transGen_self_of_wellFounded G.acyclic b) hcycle
    have hnot : ¬ TripleCollider G a b c := fun hcoll => hnot_cb hcoll.2
    simp [DirectionalTripleBlocked, TrailDir.colliderAtCurrent, TripleBlocked, hnot]
  · simp [TrailDir.edgeIntoCurrent] at hab hbc
    have hcoll : TripleCollider G a b c := ⟨hab, hbc⟩
    simp [DirectionalTripleBlocked, TrailDir.colliderAtCurrent, TripleBlocked, hcoll]
  · simp [TrailDir.edgeIntoCurrent] at hab hbc
    have hnot_ab : ¬ G.HasEdge a b := by
      intro hrev
      have hcycle : Relation.TransGen (fun u v => G.HasEdge u v) b b :=
        Relation.TransGen.head hab (Relation.TransGen.single hrev)
      exact (not_transGen_self_of_wellFounded G.acyclic b) hcycle
    have hnot : ¬ TripleCollider G a b c := fun hcoll => hnot_ab hcoll.1
    simp [DirectionalTripleBlocked, TrailDir.colliderAtCurrent, TripleBlocked, hnot]
  · simp [TrailDir.edgeIntoCurrent] at hab hbc
    have hnot_ab : ¬ G.HasEdge a b := by
      intro hrev
      have hcycle : Relation.TransGen (fun u v => G.HasEdge u v) b b :=
        Relation.TransGen.head hab (Relation.TransGen.single hrev)
      exact (not_transGen_self_of_wellFounded G.acyclic b) hcycle
    have hnot : ¬ TripleCollider G a b c := fun hcoll => hnot_ab hcoll.1
    simp [DirectionalTripleBlocked, TrailDir.colliderAtCurrent, TripleBlocked, hnot]

/--
Bayes-ball step relation over `(node, arrival-direction)` states.  A step is
available when the edge to the next node has the recorded orientation and the
local direction-only triple at the current node is not blocked by `Z`.
-/
inductive BayesBallStep (G : DAG) (Z : Finset ℕ) :
    ℕ × TrailDir → ℕ × TrailDir → Prop where
  | step {v w : ℕ} {arrival departure : TrailDir}
      (hEdge : TrailDir.edgeIntoCurrent G v w departure)
      (hopen : ¬ DirectionalTripleBlocked G Z v arrival departure) :
      BayesBallStep G Z (v, arrival) (w, departure)

/-- Reachability in the Bayes-ball state graph. -/
def BayesBallReachable (G : DAG) (Z : Finset ℕ)
    (s t : ℕ × TrailDir) : Prop :=
  Relation.ReflTransGen (BayesBallStep G Z) s t

/-- Explicit Bayes-ball paths, used when proofs need a two-step scan window. -/
inductive BayesBallPath (G : DAG) (Z : Finset ℕ) :
    ℕ × TrailDir → ℕ × TrailDir → Type where
  | nil (s : ℕ × TrailDir) : BayesBallPath G Z s s
  | cons {s t u : ℕ × TrailDir}
      (step : BayesBallStep G Z s t)
      (rest : BayesBallPath G Z t u) :
      BayesBallPath G Z s u

namespace BayesBallPath

/-- Number of Bayes-ball steps in an explicit path. -/
def length {G : DAG} {Z : Finset ℕ} :
    {s t : ℕ × TrailDir} → BayesBallPath G Z s t → ℕ
  | _, _, nil _ => 0
  | _, _, cons _ rest => rest.length + 1

/-- Forget an explicit Bayes-ball path to reflexive-transitive reachability. -/
def toReachable {G : DAG} {Z : Finset ℕ} :
    {s t : ℕ × TrailDir} → BayesBallPath G Z s t → BayesBallReachable G Z s t
  | _, _, nil _ => Relation.ReflTransGen.refl
  | _, _, cons step rest => (Relation.ReflTransGen.single step).trans rest.toReachable

/-- Append a final Bayes-ball step to an explicit path. -/
def snoc {G : DAG} {Z : Finset ℕ} {s t u : ℕ × TrailDir}
    (p : BayesBallPath G Z s t) (step : BayesBallStep G Z t u) :
    BayesBallPath G Z s u :=
  match p with
  | nil _ => cons step (nil u)
  | cons head rest => cons head (rest.snoc step)

/--
States whose node-membership proof is required by the compressed path scanner.
For a collider window `(a, _) → (b, into) → (c, outOf)`, the scanner jumps
directly from `a` to `c`, so `b` is deliberately not required here.
-/
inductive RequiredState {G : DAG} {Z : Finset ℕ} :
    {s t : ℕ × TrailDir} → BayesBallPath G Z s t → ℕ × TrailDir → Prop where
  | one {s mid : ℕ × TrailDir} (step : BayesBallStep G Z s mid) :
      RequiredState (BayesBallPath.cons step (BayesBallPath.nil mid)) mid
  | colliderTarget {s mid next finish : ℕ × TrailDir}
      {step₁ : BayesBallStep G Z s mid}
      {step₂ : BayesBallStep G Z mid next}
      {rest : BayesBallPath G Z next finish}
      (hcoll : mid.2 = TrailDir.into ∧ next.2 = TrailDir.outOf) :
      RequiredState (BayesBallPath.cons step₁ (BayesBallPath.cons step₂ rest)) next
  | colliderRest {s mid next finish : ℕ × TrailDir}
      {step₁ : BayesBallStep G Z s mid}
      {step₂ : BayesBallStep G Z mid next}
      {rest : BayesBallPath G Z next finish}
      {q : ℕ × TrailDir}
      (hcoll : mid.2 = TrailDir.into ∧ next.2 = TrailDir.outOf)
      (hreq : RequiredState rest q) :
      RequiredState (BayesBallPath.cons step₁ (BayesBallPath.cons step₂ rest)) q
  | noncolliderTarget {s mid next finish : ℕ × TrailDir}
      {step₁ : BayesBallStep G Z s mid}
      {step₂ : BayesBallStep G Z mid next}
      {rest : BayesBallPath G Z next finish}
      (hnot : ¬ (mid.2 = TrailDir.into ∧ next.2 = TrailDir.outOf)) :
      RequiredState (BayesBallPath.cons step₁ (BayesBallPath.cons step₂ rest)) mid
  | noncolliderRest {s mid next finish : ℕ × TrailDir}
      {step₁ : BayesBallStep G Z s mid}
      {step₂ : BayesBallStep G Z mid next}
      {rest : BayesBallPath G Z next finish}
      {q : ℕ × TrailDir}
      (hnot : ¬ (mid.2 = TrailDir.into ∧ next.2 = TrailDir.outOf))
      (hreq : RequiredState (BayesBallPath.cons step₂ rest) q) :
      RequiredState (BayesBallPath.cons step₁ (BayesBallPath.cons step₂ rest)) q

/-- A first target reached with `outOf` arrival is never a collider target. -/
lemma required_first_target_of_outOf {G : DAG} {Z : Finset ℕ}
    {s mid finish : ℕ × TrailDir}
    (step : BayesBallStep G Z s mid)
    (rest : BayesBallPath G Z mid finish)
    (hmid : mid.2 = TrailDir.outOf) :
    RequiredState (BayesBallPath.cons step rest) mid := by
  cases rest with
  | nil _ =>
      exact RequiredState.one step
  | cons step₂ rest₂ =>
      exact RequiredState.noncolliderTarget (by
        intro hcoll
        rw [hmid] at hcoll
        cases hcoll.1)

/-- Required states of a suffix remain required after an `outOf` first target. -/
lemma required_rest_of_outOf {G : DAG} {Z : Finset ℕ}
    {s mid finish : ℕ × TrailDir}
    (step : BayesBallStep G Z s mid)
    (rest : BayesBallPath G Z mid finish)
    (hmid : mid.2 = TrailDir.outOf)
    {q : ℕ × TrailDir}
    (hreq : RequiredState rest q) :
    RequiredState (BayesBallPath.cons step rest) q := by
  cases rest with
  | nil _ =>
      cases hreq
  | cons step₂ rest₂ =>
      exact RequiredState.noncolliderRest (by
        intro hcoll
        rw [hmid] at hcoll
        cases hcoll.1) hreq

end BayesBallPath

lemma BayesBallStep.of_active_triple {G : DAG} {Z : Finset ℕ}
    {a b c : ℕ} {arrival departure : TrailDir}
    (hab : TrailDir.edgeIntoCurrent G a b arrival)
    (hbc : TrailDir.edgeIntoCurrent G b c departure)
    (hactive : ¬ TripleBlocked G Z a b c) :
    BayesBallStep G Z (b, arrival) (c, departure) :=
  BayesBallStep.step hbc
    (by
      rwa [directionalTripleBlocked_iff_tripleBlocked hab hbc])

/-- A trail is blocked if at least one internal triple on it is blocked. -/
def TrailBlocked (G : DAG) (Z : Finset ℕ) (xs : List ℕ) : Prop :=
  ∃ a b c : ℕ, HasTriple xs a b c ∧ TripleBlocked G Z a b c

/-- A trail object is blocked by `Z`. -/
def Trail.isBlocked {G : DAG} {u v : ℕ} (Z : Finset ℕ) (t : Trail G u v) : Prop :=
  TrailBlocked G Z t.toList

/--
Opening condition for the first step of a Bayes-ball run generated from a
trail.  Trail blocking only looks at internal triples, so the first vertex must
be handled separately.
-/
def Trail.StartOpen {G : DAG} {u v : ℕ} (Z : Finset ℕ) (init_dir : TrailDir)
    (t : Trail G u v) : Prop :=
  match t with
  | Trail.nil _ => True
  | Trail.forward (u := u) _ _ =>
      ¬ DirectionalTripleBlocked G Z u init_dir TrailDir.into
  | Trail.backward (u := u) _ _ =>
      ¬ DirectionalTripleBlocked G Z u init_dir TrailDir.outOf

/-- `Z` d-separates node set `X` from node set `Y`. -/
def dSeparates (G : DAG) (X Y Z : Finset ℕ) : Prop :=
  ∀ x, x ∈ X → ∀ y, y ∈ Y → ∀ t : Trail G x y, t.isBlocked Z

/-- Standard domain for a d-separation query: `X`, `Y`, and `Z` are pairwise disjoint. -/
def DSeparationQuery (X Y Z : Finset ℕ) : Prop :=
  Disjoint X Y ∧ Disjoint X Z ∧ Disjoint Y Z

/-- `X`, `Y`, and `Z` are pairwise disjoint.
    This is the standard domain for a d-separation query
    (Oxford Graphical Models §8.3, Theorem 8.1). -/
def DisjointSets (X Y Z : Finset ℕ) : Prop :=
  Disjoint X Y ∧ Disjoint X Z ∧ Disjoint Y Z

/-- `DSeparationQuery` and `DisjointSets` are definitionally equivalent. -/
theorem DSeparationQuery_iff_DisjointSets (X Y Z : Finset ℕ) :
    DSeparationQuery X Y Z ↔ DisjointSets X Y Z :=
  Iff.rfl

namespace DAG

lemma ne_of_hasEdge (G : DAG) {u v : ℕ} (h : G.HasEdge u v) : u ≠ v := by
  intro huv
  subst v
  exact (G.acyclic.irrefl.irrefl u) (by simpa [DAG.HasEdge] using h)

lemma not_hasEdge_reverse_of_hasEdge (G : DAG) {u v : ℕ} (h : G.HasEdge u v) :
    ¬ G.HasEdge v u := by
  intro hrev
  have hcycle : Relation.TransGen (fun a b => G.HasEdge a b) u u :=
    Relation.TransGen.head h (Relation.TransGen.single hrev)
  exact (not_transGen_self_of_wellFounded G.acyclic u) hcycle

lemma mem_ancestors_self (G : DAG) {v : ℕ} (hv : v ∈ G.nodes) :
    v ∈ G.ancestors v := by
  simp [DAG.ancestors, hv, Reachable, Relation.ReflTransGen.refl]

lemma mem_ancestralSubgraphNodes_of_mem {G : DAG} {S : Finset ℕ} {v : ℕ}
    (hvS : v ∈ S) (hvG : v ∈ G.nodes) :
    v ∈ G.ancestralSubgraphNodes S := by
  exact Finset.mem_biUnion.mpr ⟨v, hvS, G.mem_ancestors_self hvG⟩

lemma mem_ancestors_of_hasEdge_of_mem_ancestors {G : DAG} {u v s : ℕ}
    (huv : G.HasEdge u v) (hvs : v ∈ G.ancestors s) :
    u ∈ G.ancestors s := by
  classical
  have huG : u ∈ G.nodes := (G.edges_subset huv).1
  have hreach_v_s : Reachable G v s := (Finset.mem_filter.mp hvs).2
  have hreach_u_s : Reachable G u s :=
    (Relation.ReflTransGen.single huv).trans hreach_v_s
  exact Finset.mem_filter.mpr ⟨huG, hreach_u_s⟩

lemma mem_ancestralSubgraphNodes_of_hasEdge_left {G : DAG} {S : Finset ℕ} {u v : ℕ}
    (huv : G.HasEdge u v) (hv : v ∈ G.ancestralSubgraphNodes S) :
    u ∈ G.ancestralSubgraphNodes S := by
  rcases Finset.mem_biUnion.mp hv with ⟨s, hsS, hvs⟩
  exact Finset.mem_biUnion.mpr
    ⟨s, hsS, mem_ancestors_of_hasEdge_of_mem_ancestors huv hvs⟩

lemma mem_dSeparationGraphNodes_of_ancestor_not_mem
    {G : DAG} {X Y Z : Finset ℕ} {v : ℕ}
    (hvA : v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z))
    (hvZ : v ∉ Z) :
    v ∈ G.dSeparationGraphNodes X Y Z := by
  exact Finset.mem_sdiff.mpr ⟨hvA, hvZ⟩

lemma mem_dSeparationGraphNodes_of_mem_left
    {G : DAG} {X Y Z : Finset ℕ} {v : ℕ}
    (hvX : v ∈ X) (hvG : v ∈ G.nodes) (hvZ : v ∉ Z) :
    v ∈ G.dSeparationGraphNodes X Y Z := by
  exact mem_dSeparationGraphNodes_of_ancestor_not_mem
    (G := G) (X := X) (Y := Y) (Z := Z)
    (DAG.mem_ancestralSubgraphNodes_of_mem
      (G := G) (S := X ∪ Y ∪ Z) (v := v) (by simp [hvX]) hvG)
    hvZ

lemma mem_dSeparationGraphNodes_of_mem_right
    {G : DAG} {X Y Z : Finset ℕ} {v : ℕ}
    (hvY : v ∈ Y) (hvG : v ∈ G.nodes) (hvZ : v ∉ Z) :
    v ∈ G.dSeparationGraphNodes X Y Z := by
  exact mem_dSeparationGraphNodes_of_ancestor_not_mem
    (G := G) (X := X) (Y := Y) (Z := Z)
    (DAG.mem_ancestralSubgraphNodes_of_mem
      (G := G) (S := X ∪ Y ∪ Z) (v := v) (by simp [hvY]) hvG)
    hvZ

lemma not_mem_right_of_disjoint_left {X Z : Finset ℕ} {v : ℕ}
    (hXZ : Disjoint X Z) (hvX : v ∈ X) :
    v ∉ Z := by
  intro hvZ
  exact (Finset.disjoint_left.mp hXZ) hvX hvZ

end DAG

lemma HasTriple.cons {xs : List ℕ} {a b c x : ℕ}
    (h : HasTriple xs a b c) :
    HasTriple (x :: xs) a b c := by
  rcases h with ⟨pre, post, hxs⟩
  exact ⟨x :: pre, post, by simp [hxs, List.cons_append]⟩

lemma TrailBlocked.cons {G : DAG} {Z : Finset ℕ} {xs : List ℕ} {x : ℕ}
    (h : TrailBlocked G Z xs) :
    TrailBlocked G Z (x :: xs) := by
  rcases h with ⟨a, b, c, htriple, hblocked⟩
  exact ⟨a, b, c, HasTriple.cons htriple, hblocked⟩

lemma not_trailBlocked_tail_of_not_trailBlocked_cons {G : DAG} {Z : Finset ℕ}
    {xs : List ℕ} {x : ℕ}
    (h : ¬ TrailBlocked G Z (x :: xs)) :
    ¬ TrailBlocked G Z xs := by
  intro htail
  exact h (TrailBlocked.cons htail)

lemma trailBlocked_of_head_tripleBlocked {G : DAG} {Z : Finset ℕ}
    {a b c : ℕ} {xs : List ℕ}
    (h : TripleBlocked G Z a b c) :
    TrailBlocked G Z (a :: b :: c :: xs) := by
  exact ⟨a, b, c, ⟨[], xs, rfl⟩, h⟩

lemma not_tripleBlocked_head_of_not_trailBlocked {G : DAG} {Z : Finset ℕ}
    {a b c : ℕ} {xs : List ℕ}
    (h : ¬ TrailBlocked G Z (a :: b :: c :: xs)) :
    ¬ TripleBlocked G Z a b c := by
  intro htriple
  exact h (trailBlocked_of_head_tripleBlocked htriple)

lemma HasTriple.head_of_trail {G : DAG} {a b c v : ℕ} (t : Trail G c v) :
    HasTriple (a :: b :: t.toList) a b c := by
  cases t with
  | nil v =>
      exact ⟨[], [], by simp [Trail.toList]⟩
  | forward h tail =>
      exact ⟨[], tail.toList, by simp [Trail.toList]⟩
  | backward h tail =>
      exact ⟨[], tail.toList, by simp [Trail.toList]⟩

lemma trailBlocked_of_head_tripleBlocked_trail {G : DAG} {Z : Finset ℕ}
    {a b c v : ℕ} (t : Trail G c v)
    (h : TripleBlocked G Z a b c) :
    TrailBlocked G Z (a :: b :: t.toList) :=
  ⟨a, b, c, HasTriple.head_of_trail t, h⟩

lemma not_tripleBlocked_head_of_not_trailBlocked_trail {G : DAG} {Z : Finset ℕ}
    {a b c v : ℕ} {t : Trail G c v}
    (h : ¬ TrailBlocked G Z (a :: b :: t.toList)) :
    ¬ TripleBlocked G Z a b c := by
  intro htriple
  exact h (trailBlocked_of_head_tripleBlocked_trail t htriple)

theorem bayesBallReachable_of_active_trail_from_prev {G : DAG} {Z : Finset ℕ}
    {prev u v : ℕ} {arrival : TrailDir}
    (hprev : TrailDir.edgeIntoCurrent G prev u arrival)
    (t : Trail G u v)
    (h_active : ¬ TrailBlocked G Z (prev :: t.toList)) :
    ∃ final_dir, BayesBallReachable G Z (u, arrival) (v, final_dir) := by
  induction t generalizing prev arrival with
  | nil v =>
      exact ⟨arrival, Relation.ReflTransGen.refl⟩
  | forward h tail ih =>
      rename_i u0 w0 v0
      have hhead : ¬ TripleBlocked G Z prev u0 w0 :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u0, arrival) (w0, TrailDir.into) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u0 :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      rcases ih (prev := u0) (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h) htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, (Relation.ReflTransGen.single hstep).trans htail⟩
  | backward h tail ih =>
      rename_i u0 w0 v0
      have hhead : ¬ TripleBlocked G Z prev u0 w0 :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u0, arrival) (w0, TrailDir.outOf) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u0 :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      rcases ih (prev := u0) (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h) htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, (Relation.ReflTransGen.single hstep).trans htail⟩

def bayesBallPath_of_active_trail_from_prev {G : DAG} {Z : Finset ℕ}
    {prev u v : ℕ} {arrival : TrailDir}
    (hprev : TrailDir.edgeIntoCurrent G prev u arrival)
    (t : Trail G u v)
    (h_active : ¬ TrailBlocked G Z (prev :: t.toList)) :
    Σ final_dir, BayesBallPath G Z (u, arrival) (v, final_dir) := by
  induction t generalizing prev arrival with
  | nil v =>
      exact ⟨arrival, BayesBallPath.nil (v, arrival)⟩
  | forward h tail ih =>
      rename_i u0 w0 v0
      have hhead : ¬ TripleBlocked G Z prev u0 w0 :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u0, arrival) (w0, TrailDir.into) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u0 :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      rcases ih (prev := u0) (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h) htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, BayesBallPath.cons hstep htail⟩
  | backward h tail ih =>
      rename_i u0 w0 v0
      have hhead : ¬ TripleBlocked G Z prev u0 w0 :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u0, arrival) (w0, TrailDir.outOf) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u0 :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      rcases ih (prev := u0) (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h) htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, BayesBallPath.cons hstep htail⟩

theorem bayesBallReachable_of_active_trail {G : DAG} {Z : Finset ℕ} {u v : ℕ}
    (t : Trail G u v)
    (h_active : ¬ t.isBlocked Z)
    (init_dir : TrailDir)
    (h_start : t.StartOpen Z init_dir) :
    ∃ final_dir, BayesBallReachable G Z (u, init_dir) (v, final_dir) := by
  cases t with
  | nil v =>
      exact ⟨init_dir, Relation.ReflTransGen.refl⟩
  | forward h tail =>
      rename_i w0
      have hstep :
          BayesBallStep G Z (u, init_dir) (w0, TrailDir.into) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by simpa [Trail.StartOpen] using h_start)
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      rcases bayesBallReachable_of_active_trail_from_prev
          (G := G) (Z := Z) (prev := u) (u := w0) (v := v)
          (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h) tail htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, (Relation.ReflTransGen.single hstep).trans htail⟩
  | backward h tail =>
      rename_i w0
      have hstep :
          BayesBallStep G Z (u, init_dir) (w0, TrailDir.outOf) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by simpa [Trail.StartOpen] using h_start)
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      rcases bayesBallReachable_of_active_trail_from_prev
          (G := G) (Z := Z) (prev := u) (u := w0) (v := v)
          (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h) tail htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, (Relation.ReflTransGen.single hstep).trans htail⟩

def bayesBallPath_of_active_trail {G : DAG} {Z : Finset ℕ} {u v : ℕ}
    (t : Trail G u v)
    (h_active : ¬ t.isBlocked Z)
    (init_dir : TrailDir)
    (h_start : t.StartOpen Z init_dir) :
    Σ final_dir, BayesBallPath G Z (u, init_dir) (v, final_dir) := by
  cases t with
  | nil v =>
      exact ⟨init_dir, BayesBallPath.nil (u, init_dir)⟩
  | forward h tail =>
      rename_i w0
      have hstep :
          BayesBallStep G Z (u, init_dir) (w0, TrailDir.into) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by simpa [Trail.StartOpen] using h_start)
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      rcases bayesBallPath_of_active_trail_from_prev
          (G := G) (Z := Z) (prev := u) (u := w0) (v := v)
          (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h) tail htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, BayesBallPath.cons hstep htail⟩
  | backward h tail =>
      rename_i w0
      have hstep :
          BayesBallStep G Z (u, init_dir) (w0, TrailDir.outOf) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by simpa [Trail.StartOpen] using h_start)
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      rcases bayesBallPath_of_active_trail_from_prev
          (G := G) (Z := Z) (prev := u) (u := w0) (v := v)
          (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h) tail htail_active with
        ⟨final_dir, htail⟩
      exact ⟨final_dir, BayesBallPath.cons hstep htail⟩

lemma Trail.startOpen_outOf_of_not_mem {G : DAG} {Z : Finset ℕ} {u v : ℕ}
    {t : Trail G u v} (huZ : u ∉ Z) :
    t.StartOpen Z TrailDir.outOf := by
  cases t <;>
    simp [Trail.StartOpen, DirectionalTripleBlocked, TrailDir.colliderAtCurrent, huZ]

theorem bayesBallReachable_of_active_trail_outOf {G : DAG} {Z : Finset ℕ}
    {u v : ℕ} (t : Trail G u v)
    (h_active : ¬ t.isBlocked Z) (huZ : u ∉ Z) :
    ∃ final_dir, BayesBallReachable G Z (u, TrailDir.outOf) (v, final_dir) :=
  bayesBallReachable_of_active_trail t h_active TrailDir.outOf
    (Trail.startOpen_outOf_of_not_mem huZ)

def bayesBallPath_of_active_trail_outOf {G : DAG} {Z : Finset ℕ}
    {u v : ℕ} (t : Trail G u v)
    (h_active : ¬ t.isBlocked Z) (huZ : u ∉ Z) :
    Σ final_dir, BayesBallPath G Z (u, TrailDir.outOf) (v, final_dir) :=
  bayesBallPath_of_active_trail t h_active TrailDir.outOf
    (Trail.startOpen_outOf_of_not_mem huZ)

lemma not_mem_Z_of_active_noncollider {G : DAG} {Z : Finset ℕ} {a b c : ℕ}
    (hactive : ¬ TripleBlocked G Z a b c)
    (hncoll : ¬ TripleCollider G a b c) :
    b ∉ Z := by
  intro hbZ
  exact hactive (Or.inl ⟨hncoll, hbZ⟩)

lemma not_mem_Z_of_active_directional_noncollider {G : DAG} {Z : Finset ℕ}
    {b : ℕ} {arrival departure : TrailDir}
    (hopen : ¬ DirectionalTripleBlocked G Z b arrival departure)
    (hnot : ¬ (arrival = TrailDir.into ∧ departure = TrailDir.outOf)) :
    b ∉ Z := by
  intro hbZ
  exact hopen (Or.inl ⟨by simpa [TrailDir.colliderAtCurrent] using hnot, hbZ⟩)

lemma collider_mem_ancestralSubgraphNodes_of_active {G : DAG} {X Y Z : Finset ℕ}
    {a b c : ℕ}
    (hactive : ¬ TripleBlocked G Z a b c)
    (hcoll : TripleCollider G a b c) :
    b ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
  classical
  have hnotDis :
      ¬ Disjoint ({b} ∪ descendants G b) Z := by
    intro hdis
    exact hactive (Or.inr ⟨hcoll, hdis⟩)
  rw [Finset.disjoint_left] at hnotDis
  push Not at hnotDis
  rcases hnotDis with ⟨z, hz_left, hzZ⟩
  have hbG : b ∈ G.nodes := (G.edges_subset hcoll.1).2
  have hreach : Reachable G b z := by
    rcases Finset.mem_union.mp hz_left with hz_single | hz_desc
    · simp at hz_single
      subst z
      exact Relation.ReflTransGen.refl
    · exact (Finset.mem_filter.mp hz_desc).2.2
  have hzS : z ∈ X ∪ Y ∪ Z := by
    simp [hzZ]
  exact Finset.mem_biUnion.mpr
    ⟨z, hzS, by simp [DAG.ancestors, hbG, hreach]⟩

/--
If a trail segment starts with a forward edge `u → w` and remains active, then
the first target `w` is ancestral to `X ∪ Y ∪ Z`, provided the trail endpoint is.
Forward chains inherit ancestry from the right; a first reversal is an active
collider and is ancestral through `Z`.
-/
lemma first_forward_target_mem_ancestral_of_active
    {G : DAG} {X Y Z : Finset ℕ} {u w v : ℕ}
    (h : G.HasEdge u w) (tail : Trail G w v)
    (h_active : ¬ TrailBlocked G Z (u :: tail.toList))
    (hvA : v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z)) :
    w ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
  induction tail generalizing u with
  | nil w =>
      simpa [Trail.toList] using hvA
  | forward h₂ tail₂ ih =>
      have htail_active :=
        not_trailBlocked_tail_of_not_trailBlocked_cons
          (by simpa [Trail.toList] using h_active)
      have hcA := ih h₂ htail_active hvA
      exact DAG.mem_ancestralSubgraphNodes_of_hasEdge_left h₂ hcA
  | backward h₂ tail₂ =>
      have hhead :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail₂)
          (by simpa [Trail.toList] using h_active)
      exact collider_mem_ancestralSubgraphNodes_of_active
        (G := G) (X := X) (Y := Y) (Z := Z) hhead ⟨h, h₂⟩

def bayesBallPathCert_of_active_trail_from_prev
    {G : DAG} {X Y Z : Finset ℕ}
    {prev u v : ℕ} {arrival : TrailDir}
    (hprev : TrailDir.edgeIntoCurrent G prev u arrival)
    (t : Trail G u v)
    (h_active : ¬ TrailBlocked G Z (prev :: t.toList))
    (huA : u ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z))
    (hvD : v ∈ G.dSeparationGraphNodes X Y Z) :
    Σ final_dir, {p : BayesBallPath G Z (u, arrival) (v, final_dir) //
      ∀ {q : ℕ × TrailDir}, BayesBallPath.RequiredState p q →
        q.1 ∈ G.dSeparationGraphNodes X Y Z} := by
  induction t generalizing prev arrival with
  | nil v =>
      refine ⟨arrival, ⟨BayesBallPath.nil (v, arrival), ?_⟩⟩
      intro q hreq
      cases hreq
  | forward h tail ih =>
      rename_i u₀ w₀ v₀
      have hhead : ¬ TripleBlocked G Z prev u₀ w₀ :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u₀, arrival) (w₀, TrailDir.into) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u₀ :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      have hvA : v₀ ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        (Finset.mem_sdiff.mp (by
          simpa [DAG.dSeparationGraphNodes] using hvD)).1
      have hwA : w₀ ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        first_forward_target_mem_ancestral_of_active
          (G := G) (X := X) (Y := Y) (Z := Z)
          h tail htail_active hvA
      rcases ih (prev := u₀) (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h)
          htail_active hwA hvD with
        ⟨final_dir, ⟨ptail, hreq_tail⟩⟩
      refine ⟨final_dir, ⟨BayesBallPath.cons hstep ptail, ?_⟩⟩
      intro q hreq
      cases ptail with
      | nil s =>
          cases hreq with
          | one _ =>
              simpa using hvD
      | cons step₂ rest =>
          cases hreq with
          | colliderTarget hcoll =>
              exact hreq_tail
                (BayesBallPath.required_first_target_of_outOf step₂ rest hcoll.2)
          | colliderRest hcoll hrest =>
              exact hreq_tail
                (BayesBallPath.required_rest_of_outOf step₂ rest hcoll.2 hrest)
          | noncolliderTarget hnot =>
              cases step₂ with
              | step hEdge hopen =>
                  have hwZ : w₀ ∉ Z :=
                    not_mem_Z_of_active_directional_noncollider hopen hnot
                  exact DAG.mem_dSeparationGraphNodes_of_ancestor_not_mem hwA hwZ
          | noncolliderRest _ htailReq =>
              exact hreq_tail htailReq
  | backward h tail ih =>
      rename_i u₀ w₀ v₀
      have hhead : ¬ TripleBlocked G Z prev u₀ w₀ :=
        not_tripleBlocked_head_of_not_trailBlocked_trail (t := tail) h_active
      have hstep :
          BayesBallStep G Z (u₀, arrival) (w₀, TrailDir.outOf) := by
        exact BayesBallStep.of_active_triple hprev
          (by simpa [TrailDir.edgeIntoCurrent] using h) hhead
      have htail_active : ¬ TrailBlocked G Z (u₀ :: tail.toList) :=
        not_trailBlocked_tail_of_not_trailBlocked_cons h_active
      have hwA : w₀ ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        DAG.mem_ancestralSubgraphNodes_of_hasEdge_left h huA
      rcases ih (prev := u₀) (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h)
          htail_active hwA hvD with
        ⟨final_dir, ⟨ptail, hreq_tail⟩⟩
      refine ⟨final_dir, ⟨BayesBallPath.cons hstep ptail, ?_⟩⟩
      intro q hreq
      cases ptail with
      | nil s =>
          cases hreq with
          | one _ =>
              simpa using hvD
      | cons step₂ rest =>
          cases hreq with
          | colliderTarget hcoll =>
              cases hcoll.1
          | colliderRest hcoll _ =>
              cases hcoll.1
          | noncolliderTarget hnot =>
              cases step₂ with
              | step hEdge hopen =>
                  have hwZ : w₀ ∉ Z :=
                    not_mem_Z_of_active_directional_noncollider hopen hnot
                  exact DAG.mem_dSeparationGraphNodes_of_ancestor_not_mem hwA hwZ
          | noncolliderRest _ htailReq =>
              exact hreq_tail htailReq

def bayesBallPathCert_of_active_trail_outOf
    {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ}
    (t : Trail G u v)
    (h_active : ¬ t.isBlocked Z)
    (huZ : u ∉ Z)
    (huA : u ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z))
    (hvD : v ∈ G.dSeparationGraphNodes X Y Z) :
    Σ final_dir, {p : BayesBallPath G Z (u, TrailDir.outOf) (v, final_dir) //
      ∀ {q : ℕ × TrailDir}, BayesBallPath.RequiredState p q →
        q.1 ∈ G.dSeparationGraphNodes X Y Z} := by
  cases t with
  | nil v =>
      refine ⟨TrailDir.outOf, ⟨BayesBallPath.nil (u, TrailDir.outOf), ?_⟩⟩
      intro q hreq
      cases hreq
  | forward h tail =>
      rename_i w₀
      have hstep :
          BayesBallStep G Z (u, TrailDir.outOf) (w₀, TrailDir.into) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by
            simpa [Trail.StartOpen] using
              (Trail.startOpen_outOf_of_not_mem (G := G) (Z := Z)
                (u := u) (v := v)
                (t := Trail.forward h tail) huZ))
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      have hvA : v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        (Finset.mem_sdiff.mp (by
          simpa [DAG.dSeparationGraphNodes] using hvD)).1
      have hwA : w₀ ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        first_forward_target_mem_ancestral_of_active
          (G := G) (X := X) (Y := Y) (Z := Z)
          h tail htail_active hvA
      rcases bayesBallPathCert_of_active_trail_from_prev
          (G := G) (X := X) (Y := Y) (Z := Z)
          (prev := u) (u := w₀) (v := v) (arrival := TrailDir.into)
          (by simpa [TrailDir.edgeIntoCurrent] using h)
          tail htail_active hwA hvD with
        ⟨final_dir, ⟨ptail, hreq_tail⟩⟩
      refine ⟨final_dir, ⟨BayesBallPath.cons hstep ptail, ?_⟩⟩
      intro q hreq
      cases ptail with
      | nil s =>
          cases hreq with
          | one _ =>
              simpa using hvD
      | cons step₂ rest =>
          cases hreq with
          | colliderTarget hcoll =>
              exact hreq_tail
                (BayesBallPath.required_first_target_of_outOf step₂ rest hcoll.2)
          | colliderRest hcoll hrest =>
              exact hreq_tail
                (BayesBallPath.required_rest_of_outOf step₂ rest hcoll.2 hrest)
          | noncolliderTarget hnot =>
              cases step₂ with
              | step hEdge hopen =>
                  have hwZ : w₀ ∉ Z :=
                    not_mem_Z_of_active_directional_noncollider hopen hnot
                  exact DAG.mem_dSeparationGraphNodes_of_ancestor_not_mem hwA hwZ
          | noncolliderRest _ htailReq =>
              exact hreq_tail htailReq
  | backward h tail =>
      rename_i w₀
      have hstep :
          BayesBallStep G Z (u, TrailDir.outOf) (w₀, TrailDir.outOf) :=
        BayesBallStep.step (by simpa [TrailDir.edgeIntoCurrent] using h)
          (by
            simpa [Trail.StartOpen] using
              (Trail.startOpen_outOf_of_not_mem (G := G) (Z := Z)
                (u := u) (v := v)
                (t := Trail.backward h tail) huZ))
      have htail_active : ¬ TrailBlocked G Z (u :: tail.toList) := by
        simpa [Trail.isBlocked, Trail.toList] using h_active
      have hwA : w₀ ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        DAG.mem_ancestralSubgraphNodes_of_hasEdge_left h huA
      rcases bayesBallPathCert_of_active_trail_from_prev
          (G := G) (X := X) (Y := Y) (Z := Z)
          (prev := u) (u := w₀) (v := v) (arrival := TrailDir.outOf)
          (by simpa [TrailDir.edgeIntoCurrent] using h)
          tail htail_active hwA hvD with
        ⟨final_dir, ⟨ptail, hreq_tail⟩⟩
      refine ⟨final_dir, ⟨BayesBallPath.cons hstep ptail, ?_⟩⟩
      intro q hreq
      cases ptail with
      | nil s =>
          cases hreq with
          | one _ =>
              simpa using hvD
      | cons step₂ rest =>
          cases hreq with
          | colliderTarget hcoll =>
              cases hcoll.1
          | colliderRest hcoll _ =>
              cases hcoll.1
          | noncolliderTarget hnot =>
              cases step₂ with
              | step hEdge hopen =>
                  have hwZ : w₀ ∉ Z :=
                    not_mem_Z_of_active_directional_noncollider hopen hnot
                  exact DAG.mem_dSeparationGraphNodes_of_ancestor_not_mem hwA hwZ
          | noncolliderRest _ htailReq =>
              exact hreq_tail htailReq

/--
Reachability in the moralized ancestral graph, packaged as explicit "large
steps": either a direct underlying DAG edge survives deletion of `Z`, or two
co-parents are connected by the moralization jump.
-/
inductive MAGWalk (G : DAG) (X Y Z : Finset ℕ) : ℕ → ℕ → Prop where
  | refl (u : ℕ) : MAGWalk G X Y Z u u
  | single {u v : ℕ}
      (hEdge : G.HasEdge u v ∨ G.HasEdge v u)
      (hu : u ∈ G.dSeparationGraphNodes X Y Z)
      (hv : v ∈ G.dSeparationGraphNodes X Y Z) :
      MAGWalk G X Y Z u v
  | jump {u v w : ℕ}
      (huw : G.HasEdge u w)
      (hvw : G.HasEdge v w)
      (hne : u ≠ v)
      (hu : u ∈ G.dSeparationGraphNodes X Y Z)
      (hv : v ∈ G.dSeparationGraphNodes X Y Z)
      (hw : w ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z)) :
      MAGWalk G X Y Z u v
  | trans {u v w : ℕ}
      (huv : MAGWalk G X Y Z u v)
      (hvw : MAGWalk G X Y Z v w) :
      MAGWalk G X Y Z u w

lemma mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes
    {G : DAG} {X Y Z : Finset ℕ} {v : ℕ}
    (hv : v ∈ G.dSeparationGraphNodes X Y Z) :
    v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
  exact (Finset.mem_sdiff.mp (by simpa [DAG.dSeparationGraphNodes] using hv)).1

lemma dSeparationGraph_adj_of_mag_single {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ}
    (hEdge : G.HasEdge u v ∨ G.HasEdge v u)
    (hu : u ∈ G.dSeparationGraphNodes X Y Z)
    (hv : v ∈ G.dSeparationGraphNodes X Y Z) :
    (G.dSeparationGraph X Y Z).Adj u v := by
  let S := X ∪ (Y ∪ Z)
  have huA : u ∈ G.ancestralSubgraphNodes S := by
    simpa [S] using mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes (G := G) (X := X)
      (Y := Y) (Z := Z) hu
  have hvA : v ∈ G.ancestralSubgraphNodes S := by
    simpa [S] using mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes (G := G) (X := X)
      (Y := Y) (Z := Z) hv
  have hne : u ≠ v := by
    rcases hEdge with huv | hvu
    · exact G.ne_of_hasEdge huv
    · exact Ne.symm (G.ne_of_hasEdge hvu)
  have huA0 : u ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
    simpa [S, Finset.union_assoc] using huA
  have hvA0 : v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
    simpa [S, Finset.union_assoc] using hvA
  refine ⟨hu, hv, ?_⟩
  dsimp [DAG.moralGraph]
  refine ⟨huA0, hvA0, hne, ?_⟩
  rcases hEdge with huv | hvu
  · left
    exact Finset.mem_filter.mpr ⟨by simpa [DAG.HasEdge] using huv, huA0, hvA0⟩
  · right
    left
    exact Finset.mem_filter.mpr ⟨by simpa [DAG.HasEdge] using hvu, hvA0, huA0⟩

lemma dSeparationGraph_adj_of_mag_jump {G : DAG} {X Y Z : Finset ℕ} {u v w : ℕ}
    (huw : G.HasEdge u w)
    (hvw : G.HasEdge v w)
    (hne : u ≠ v)
    (hu : u ∈ G.dSeparationGraphNodes X Y Z)
    (hv : v ∈ G.dSeparationGraphNodes X Y Z)
    (hw : w ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z)) :
    (G.dSeparationGraph X Y Z).Adj u v := by
  let S := X ∪ (Y ∪ Z)
  have huA : u ∈ G.ancestralSubgraphNodes S := by
    simpa [S] using mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes (G := G) (X := X)
      (Y := Y) (Z := Z) hu
  have hvA : v ∈ G.ancestralSubgraphNodes S := by
    simpa [S] using mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes (G := G) (X := X)
      (Y := Y) (Z := Z) hv
  have hwA : w ∈ G.ancestralSubgraphNodes S := by
    simpa [S] using hw
  have huA0 : u ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
    simpa [S, Finset.union_assoc] using huA
  have hvA0 : v ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
    simpa [S, Finset.union_assoc] using hvA
  have hwA0 : w ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) := by
    simpa [S, Finset.union_assoc] using hwA
  refine ⟨hu, hv, ?_⟩
  dsimp [DAG.moralGraph]
  refine ⟨huA0, hvA0, hne, Or.inr (Or.inr ?_)⟩
  refine ⟨w, ?_, ?_, hne⟩
  · exact Finset.mem_filter.mpr ⟨by simpa [DAG.HasEdge] using huw, huA0, hwA0⟩
  · exact Finset.mem_filter.mpr ⟨by simpa [DAG.HasEdge] using hvw, hvA0, hwA0⟩

theorem MAGWalk.to_dSeparationGraph_reachable {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ}
    (h : MAGWalk G X Y Z u v) :
    (G.dSeparationGraph X Y Z).Reachable u v := by
  induction h with
  | refl u =>
      exact SimpleGraph.Reachable.refl u
  | single hEdge hu hv =>
      exact SimpleGraph.Adj.reachable (dSeparationGraph_adj_of_mag_single hEdge hu hv)
  | jump huw hvw hne hu hv hw =>
      exact SimpleGraph.Adj.reachable (dSeparationGraph_adj_of_mag_jump huw hvw hne hu hv hw)
  | trans _ _ ihuv ihvw =>
      exact SimpleGraph.Reachable.trans ihuv ihvw

lemma mag_single_or_jump_of_dSeparationGraph_adj {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ}
    (h : (G.dSeparationGraph X Y Z).Adj u v) :
    MAGWalk G X Y Z u v := by
  let S := X ∪ (Y ∪ Z)
  rcases h with ⟨hu, hv, hmoral⟩
  dsimp [DAG.moralGraph] at hmoral
  rcases hmoral with ⟨_, _, hne, hdir | hrev | hcop⟩
  · have hmem :
        (u, v) ∈ G.edges.filter (fun e =>
          e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S) := by
        simpa [DAG.ancestralSubgraph, DAG.HasEdge, S] using hdir
    exact MAGWalk.single (G := G) (X := X) (Y := Y) (Z := Z)
      (Or.inl (by simpa [DAG.HasEdge] using (Finset.mem_filter.mp hmem).1)) hu hv
  · have hmem :
        (v, u) ∈ G.edges.filter (fun e =>
          e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S) := by
        simpa [DAG.ancestralSubgraph, DAG.HasEdge, S] using hrev
    exact MAGWalk.single (G := G) (X := X) (Y := Y) (Z := Z)
      (Or.inr (by simpa [DAG.HasEdge] using (Finset.mem_filter.mp hmem).1)) hu hv
  · rcases hcop with ⟨w, huw', hvw', huw_ne_v⟩
    have huw_mem :
        (u, w) ∈ G.edges.filter (fun e =>
          e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S) := by
        simpa [DAG.ancestralSubgraph, DAG.HasEdge, S] using huw'
    have hvw_mem :
        (v, w) ∈ G.edges.filter (fun e =>
          e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S) := by
        simpa [DAG.ancestralSubgraph, DAG.HasEdge, S] using hvw'
    exact MAGWalk.jump (G := G) (X := X) (Y := Y) (Z := Z)
      (by simpa [DAG.HasEdge] using (Finset.mem_filter.mp huw_mem).1)
      (by simpa [DAG.HasEdge] using (Finset.mem_filter.mp hvw_mem).1)
      huw_ne_v hu hv (by
        simpa [S] using (Finset.mem_filter.mp huw_mem).2.2)

theorem MAGWalk.of_dSeparationGraph_reachable {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ}
    (h : (G.dSeparationGraph X Y Z).Reachable u v) :
    MAGWalk G X Y Z u v := by
  rcases h with ⟨p⟩
  induction p with
  | nil =>
      exact MAGWalk.refl _
  | cons hAdj _ ih =>
      exact MAGWalk.trans (mag_single_or_jump_of_dSeparationGraph_adj hAdj) ih

theorem magWalk_iff_dSeparationGraph_reachable {G : DAG} {X Y Z : Finset ℕ} {u v : ℕ} :
    MAGWalk G X Y Z u v ↔ (G.dSeparationGraph X Y Z).Reachable u v :=
  ⟨MAGWalk.to_dSeparationGraph_reachable, MAGWalk.of_dSeparationGraph_reachable⟩

lemma MAGWalk.jump_of_active_collider {G : DAG} {X Y Z : Finset ℕ} {u x w : ℕ}
    (hux : G.HasEdge u x)
    (hwx : G.HasEdge w x)
    (hactive : ¬ TripleBlocked G Z u x w)
    (hu : u ∈ G.dSeparationGraphNodes X Y Z)
    (hw : w ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z u w := by
  by_cases huw : u = w
  · subst w
    exact MAGWalk.refl u
  · exact MAGWalk.jump hux hwx huw hu hw
      (collider_mem_ancestralSubgraphNodes_of_active hactive ⟨hux, hwx⟩)

lemma MAGWalk.single_of_bayesBallStep {G : DAG} {X Y Z : Finset ℕ}
    {u v : ℕ} {arrival departure : TrailDir}
    (hstep : BayesBallStep G Z (u, arrival) (v, departure))
    (hu : u ∈ G.dSeparationGraphNodes X Y Z)
    (hv : v ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z u v := by
  cases hstep with
  | step hEdge _ =>
      cases departure
      · exact MAGWalk.single
          (Or.inl (by simpa [TrailDir.edgeIntoCurrent] using hEdge)) hu hv
      · exact MAGWalk.single
          (Or.inr (by simpa [TrailDir.edgeIntoCurrent] using hEdge)) hu hv

lemma MAGWalk.jump_of_bayesBall_collider {G : DAG} {X Y Z : Finset ℕ}
    {a b c : ℕ} {arrival : TrailDir}
    (hInto : BayesBallStep G Z (a, arrival) (b, TrailDir.into))
    (hOut : BayesBallStep G Z (b, TrailDir.into) (c, TrailDir.outOf))
    (ha : a ∈ G.dSeparationGraphNodes X Y Z)
    (hc : c ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z a c := by
  cases hInto with
  | step hIntoEdge _ =>
      cases hOut with
      | step hOutEdge hOutOpen =>
          have hactive : ¬ TripleBlocked G Z a b c := by
            intro hblocked
            exact hOutOpen
              ((directionalTripleBlocked_iff_tripleBlocked hIntoEdge hOutEdge).mpr hblocked)
          have hcoll : TripleCollider G a b c := by
            exact ⟨by simpa [TrailDir.edgeIntoCurrent] using hIntoEdge,
              by simpa [TrailDir.edgeIntoCurrent] using hOutEdge⟩
          have hb : b ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
            collider_mem_ancestralSubgraphNodes_of_active hactive hcoll
          by_cases hac : a = c
          · subst c
            exact MAGWalk.refl a
          · exact MAGWalk.jump
              (by simpa [TrailDir.edgeIntoCurrent] using hIntoEdge)
              (by simpa [TrailDir.edgeIntoCurrent] using hOutEdge)
              hac ha hc hb

/--
Compressed Bayes-ball-to-MAG step for an active collider.  The middle collider
`b` is not required to survive deletion of `Z`; its active-open premise supplies
ancestral membership, and the MAG step jumps directly from `a` to `c`.
-/
lemma MAGWalk.trans_jump_of_bayesBall_collider {G : DAG} {X Y Z : Finset ℕ}
    {r a b c : ℕ} {arrival : TrailDir}
    (hprefix : MAGWalk G X Y Z r a)
    (hInto : BayesBallStep G Z (a, arrival) (b, TrailDir.into))
    (hOut : BayesBallStep G Z (b, TrailDir.into) (c, TrailDir.outOf))
    (ha : a ∈ G.dSeparationGraphNodes X Y Z)
    (hc : c ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z r c :=
  MAGWalk.trans hprefix
    (MAGWalk.jump_of_bayesBall_collider hInto hOut ha hc)

namespace BayesBallPath

/--
Compress an explicit Bayes-ball path to a `MAGWalk`, scanning with a two-step
window.  Non-collider windows consume one step as a `MAGWalk.single`; collider
windows of the form `(a, _) → (b, into) → (c, outOf)` consume two steps as one
`MAGWalk.jump`, so the skipped collider `b` need not be present in
`dSeparationGraphNodes`.
-/
def compressWithFuel {G : DAG} {X Y Z : Finset ℕ} :
    (fuel : ℕ) →
    {s t : ℕ × TrailDir} →
    (p : BayesBallPath G Z s t) →
    p.length ≤ fuel →
    s.1 ∈ G.dSeparationGraphNodes X Y Z →
    t.1 ∈ G.dSeparationGraphNodes X Y Z →
    (∀ {q : ℕ × TrailDir}, RequiredState p q →
      q.1 ∈ G.dSeparationGraphNodes X Y Z) →
    MAGWalk G X Y Z s.1 t.1
  | 0, s, _, nil _, _, hs, _, _ =>
      MAGWalk.refl s.1
  | 0, _, _, cons step rest, hfuel, _, _, _ => by
      simp [BayesBallPath.length] at hfuel
  | _ + 1, s, _, nil _, _, hs, _, _ =>
      MAGWalk.refl s.1
  | _ + 1, _, _, cons step (nil _), _, hs, ht, _ =>
      MAGWalk.single_of_bayesBallStep step hs ht
  | fuel + 1, _, _, cons (s := start) (t := mid) step₁
      (cons (s := _) (t := next) step₂ rest), hfuel, hs, ht, hreq => by
      rcases start with ⟨a, arrA⟩
      rcases mid with ⟨b, arrB⟩
      rcases next with ⟨c, arrC⟩
      by_cases hcoll : arrB = TrailDir.into ∧ arrC = TrailDir.outOf
      · have hc : c ∈ G.dSeparationGraphNodes X Y Z :=
          hreq (q := (c, arrC))
            (RequiredState.colliderTarget
              (G := G) (Z := Z) (s := (a, arrA)) (mid := (b, arrB))
              (next := (c, arrC)) (step₁ := step₁) (step₂ := step₂)
              (rest := rest) hcoll)
        rcases hcoll with ⟨harrB, harrC⟩
        subst arrB
        subst arrC
        have hreq_rest :
            ∀ {q : ℕ × TrailDir}, RequiredState rest q →
              q.1 ∈ G.dSeparationGraphNodes X Y Z := by
          intro q hq
          exact hreq (q := q)
            (RequiredState.colliderRest
              (G := G) (Z := Z) (s := (a, arrA))
              (mid := (b, TrailDir.into)) (next := (c, TrailDir.outOf))
              (step₁ := step₁) (step₂ := step₂) (rest := rest)
              ⟨rfl, rfl⟩ hq)
        have hfuel_rest : rest.length ≤ fuel := by
          simp [BayesBallPath.length] at hfuel ⊢
          omega
        exact MAGWalk.trans
          (MAGWalk.jump_of_bayesBall_collider
            (G := G) (X := X) (Y := Y) (Z := Z)
            (a := a) (b := b) (c := c) (arrival := arrA)
            step₁ step₂ hs hc)
          (compressWithFuel fuel rest hfuel_rest hc ht hreq_rest)
      · have hb : b ∈ G.dSeparationGraphNodes X Y Z :=
          hreq (q := (b, arrB))
            (RequiredState.noncolliderTarget
              (G := G) (Z := Z) (s := (a, arrA)) (mid := (b, arrB))
              (next := (c, arrC)) (step₁ := step₁) (step₂ := step₂)
              (rest := rest) hcoll)
        have hreq_tail :
            ∀ {q : ℕ × TrailDir}, RequiredState (cons step₂ rest) q →
              q.1 ∈ G.dSeparationGraphNodes X Y Z := by
          intro q hq
          exact hreq (q := q)
            (RequiredState.noncolliderRest
              (G := G) (Z := Z) (s := (a, arrA)) (mid := (b, arrB))
              (next := (c, arrC)) (step₁ := step₁) (step₂ := step₂)
              (rest := rest) hcoll hq)
        have hfuel_tail : (cons step₂ rest).length ≤ fuel := by
          simp [BayesBallPath.length] at hfuel ⊢
          omega
        exact MAGWalk.trans
          (MAGWalk.single_of_bayesBallStep
            (G := G) (X := X) (Y := Y) (Z := Z)
            (u := a) (v := b) (arrival := arrA) (departure := arrB)
            step₁ hs hb)
          (compressWithFuel fuel (cons step₂ rest) hfuel_tail hb ht hreq_tail)

/-- Fuel-free wrapper for the compressed Bayes-ball path scanner. -/
def compress {G : DAG} {X Y Z : Finset ℕ} {s t : ℕ × TrailDir}
    (p : BayesBallPath G Z s t)
    (hs : s.1 ∈ G.dSeparationGraphNodes X Y Z)
    (ht : t.1 ∈ G.dSeparationGraphNodes X Y Z)
    (hreq : ∀ {q : ℕ × TrailDir}, RequiredState p q →
      q.1 ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z s.1 t.1 :=
  compressWithFuel p.length p le_rfl hs ht hreq

end BayesBallPath

lemma magWalk_of_bayesBall_pair {G : DAG} {X Y Z : Finset ℕ}
    {s t : ℕ × TrailDir}
    (h_bb : BayesBallReachable G Z s t)
    (hmem : ∀ {n : ℕ} {d : TrailDir},
      BayesBallReachable G Z s (n, d) →
        n ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z s.1 t.1 := by
  induction h_bb with
  | refl =>
      exact MAGWalk.refl s.1
  | tail hreach hstep ih =>
      rename_i current target
      rcases current with ⟨n, arrival⟩
      rcases target with ⟨w, departure⟩
      cases hstep with
      | step hEdge hopen =>
          have hn : n ∈ G.dSeparationGraphNodes X Y Z := hmem hreach
          have hnext :
              BayesBallReachable G Z s (w, departure) :=
            hreach.trans (Relation.ReflTransGen.single
              (BayesBallStep.step (G := G) (Z := Z) hEdge hopen))
          have hw : w ∈ G.dSeparationGraphNodes X Y Z := hmem hnext
          exact MAGWalk.trans ih
            (MAGWalk.single_of_bayesBallStep
              (G := G) (X := X) (Y := Y) (Z := Z)
              (u := n) (v := w) (arrival := arrival) (departure := departure)
              (BayesBallStep.step hEdge hopen) hn hw)

lemma magWalk_of_bayesBall {G : DAG} {X Y Z : Finset ℕ}
    {u v : ℕ} {d₁ d₂ : TrailDir}
    (h_bb : BayesBallReachable G Z (u, d₁) (v, d₂))
    (hmem : ∀ {n : ℕ} {d : TrailDir},
      BayesBallReachable G Z (u, d₁) (n, d) →
        n ∈ G.dSeparationGraphNodes X Y Z) :
    MAGWalk G X Y Z u v :=
  magWalk_of_bayesBall_pair h_bb hmem

theorem dSeparationGraph_reachable_of_active_trail_disjoint
    {G : DAG} {X Y Z : Finset ℕ} {x y : ℕ}
    (hXZ : Disjoint X Z) (hYZ : Disjoint Y Z)
    (hxX : x ∈ X) (hyY : y ∈ Y)
    (t : Trail G x y) (h_active : ¬ t.isBlocked Z) :
    (G.dSeparationGraph X Y Z).Reachable x y := by
  have hxZ : x ∉ Z := DAG.not_mem_right_of_disjoint_left hXZ hxX
  have hyZ : y ∉ Z := DAG.not_mem_right_of_disjoint_left hYZ hyY
  cases t with
  | nil x =>
      exact SimpleGraph.Reachable.refl x
  | forward h tail =>
      rename_i w
      have hxG : x ∈ G.nodes := (G.edges_subset h).1
      have hyG : y ∈ G.nodes :=
        Trail.target_mem_graph_nodes_of_source_mem
          (Trail.forward (G := G) (u := x) (w := w) (v := y) h tail) hxG
      have hxD : x ∈ G.dSeparationGraphNodes X Y Z :=
        DAG.mem_dSeparationGraphNodes_of_mem_left hxX hxG hxZ
      have hyD : y ∈ G.dSeparationGraphNodes X Y Z :=
        DAG.mem_dSeparationGraphNodes_of_mem_right hyY hyG hyZ
      have hxA : x ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes hxD
      rcases bayesBallPathCert_of_active_trail_outOf
          (G := G) (X := X) (Y := Y) (Z := Z)
          (u := x) (v := y)
          (Trail.forward (G := G) (u := x) (w := w) (v := y) h tail)
          h_active hxZ hxA hyD with
        ⟨final_dir, ⟨p, hreq⟩⟩
      exact MAGWalk.to_dSeparationGraph_reachable
        (BayesBallPath.compress
          (G := G) (X := X) (Y := Y) (Z := Z)
          (s := (x, TrailDir.outOf)) (t := (y, final_dir))
          p hxD hyD hreq)
  | backward h tail =>
      rename_i w
      have hxG : x ∈ G.nodes := (G.edges_subset h).2
      have hyG : y ∈ G.nodes :=
        Trail.target_mem_graph_nodes_of_source_mem
          (Trail.backward (G := G) (u := x) (w := w) (v := y) h tail) hxG
      have hxD : x ∈ G.dSeparationGraphNodes X Y Z :=
        DAG.mem_dSeparationGraphNodes_of_mem_left hxX hxG hxZ
      have hyD : y ∈ G.dSeparationGraphNodes X Y Z :=
        DAG.mem_dSeparationGraphNodes_of_mem_right hyY hyG hyZ
      have hxA : x ∈ G.ancestralSubgraphNodes (X ∪ Y ∪ Z) :=
        mem_ancestralSubgraphNodes_of_mem_dSeparationGraphNodes hxD
      rcases bayesBallPathCert_of_active_trail_outOf
          (G := G) (X := X) (Y := Y) (Z := Z)
          (u := x) (v := y)
          (Trail.backward (G := G) (u := x) (w := w) (v := y) h tail)
          h_active hxZ hxA hyD with
        ⟨final_dir, ⟨p, hreq⟩⟩
      exact MAGWalk.to_dSeparationGraph_reachable
        (BayesBallPath.compress
          (G := G) (X := X) (Y := Y) (Z := Z)
          (s := (x, TrailDir.outOf)) (t := (y, final_dir))
          p hxD hyD hreq)

theorem dsep_complete_of_endpoint_disjoint
    {G : DAG} {X Y Z : Finset ℕ}
    (hXZ : Disjoint X Z) (hYZ : Disjoint Y Z) :
    DAG.dSeparated G X Y Z → dSeparates G X Y Z := by
  intro hdsep x hxX y hyY t
  by_contra h_active
  exact hdsep x hxX y hyY
    (dSeparationGraph_reachable_of_active_trail_disjoint
      (G := G) (X := X) (Y := Y) (Z := Z)
      hXZ hYZ hxX hyY t h_active)

theorem dsep_complete_of_query
    {G : DAG} {X Y Z : Finset ℕ}
    (hquery : DSeparationQuery X Y Z) :
    DAG.dSeparated G X Y Z → dSeparates G X Y Z :=
  dsep_complete_of_endpoint_disjoint hquery.2.1 hquery.2.2

/-- **Soundness of d-separation under pairwise-disjoint domain.**
    If `X`, `Y`, `Z` are pairwise disjoint (`DisjointSets X Y Z`) and the
    moralized ancestral graph separates `X` from `Y` after deleting `Z`
    (`DAG.dSeparated G X Y Z`), then every trail from `X` to `Y` is blocked
    by `Z` (`dSeparates G X Y Z`).

    This is the reliability (completeness) direction: moral-graph separation
    implies trail blocking.  The proof follows the three-stage pipeline:
    1. `bayesBallPath_of_active_trail_outOf` lifts an active trail to a
       Bayes-ball path (possible because endpoint-disjointness keeps the
       start node out of `Z`).
    2. `bayesBallPathCert_of_active_trail_outOf` certifies that every
       `RequiredState` node survives deletion of `Z`.
    3. `BayesBallPath.compress` turns the path into a `MAGWalk`, and
       `MAGWalk.to_dSeparationGraph_reachable` yields reachability in the
       moralized graph, contradicting `DAG.dSeparated`.

    The unrestricted converse is false: see
    `dsep_complete_endpoint_in_Z_counterexample`. -/
theorem dSeparated_of_dSeparated_disjoint
    {G : DAG} {X Y Z : Finset ℕ}
    (hXYZ : DisjointSets X Y Z)
    (hsep : DAG.dSeparated G X Y Z) : dSeparates G X Y Z := by
  exact dsep_complete_of_endpoint_disjoint hXYZ.2.1 hXYZ.2.2 hsep

/-! ## Small checkable examples -/

namespace DAGExamples

/-- The chain `0 → 1 → 2`. -/
def chain3 : DAG :=
  DAG.ofRank ({0, 1, 2} : Finset ℕ) ({(0, 1), (1, 2)} : Finset (ℕ × ℕ)) id
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)

/-- The fork `1 → 0` and `1 → 2`. -/
def fork3 : DAG :=
  DAG.ofRank ({0, 1, 2} : Finset ℕ) ({(1, 0), (1, 2)} : Finset (ℕ × ℕ))
    (fun n => if n = 1 then 0 else 1)
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)

/-- The collider `0 → 1 ← 2`. -/
def collider3 : DAG :=
  DAG.ofRank ({0, 1, 2} : Finset ℕ) ({(0, 1), (2, 1)} : Finset (ℕ × ℕ))
    (fun n => if n = 1 then 1 else 0)
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)
    (by
      intro u v h
      simp at h
      rcases h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;> simp)

example : parents chain3 1 = {0} := by
  decide

example : children chain3 1 = {2} := by
  decide

example : (chain3.deleteLeaf 2).nodes = ({0, 1} : Finset ℕ) := by
  decide

example : (chain3.deleteLeaf 2).edges = ({(0, 1)} : Finset (ℕ × ℕ)) := by
  decide

example : (chain3.deleteLeaf 2).nodes.card < chain3.nodes.card :=
  DAG.deleteLeaf_card_lt (G := chain3) (v := 2) (by decide)

def chainTrail02 : Trail chain3 0 2 :=
  Trail.forward (u := 0) (w := 1) (v := 2)
    (by
      change (0, 1) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ))
      simp)
    (Trail.forward (u := 1) (w := 2) (v := 2)
      (by
        change (1, 2) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ))
        simp)
      (Trail.nil 2))

example : chainTrail02.isBlocked ({1} : Finset ℕ) := by
  unfold Trail.isBlocked TrailBlocked TripleBlocked TripleCollider HasTriple
  refine ⟨0, 1, 2, ?_, ?_⟩
  · refine ⟨[], [], ?_⟩
    simp [chainTrail02, Trail.toList]
  · left
    constructor
    · change ¬
        ((0, 1) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ)) ∧
          (2, 1) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ)))
      simp
    · simp

def colliderTrail02 : Trail collider3 0 2 :=
  Trail.forward (u := 0) (w := 1) (v := 2)
    (by
      change (0, 1) ∈ ({(0, 1), (2, 1)} : Finset (ℕ × ℕ))
      simp)
    (Trail.backward (u := 1) (w := 2) (v := 2)
      (by
        change (2, 1) ∈ ({(0, 1), (2, 1)} : Finset (ℕ × ℕ))
        simp)
      (Trail.nil 2))

example : colliderTrail02.isBlocked (∅ : Finset ℕ) := by
  unfold Trail.isBlocked TrailBlocked TripleBlocked TripleCollider HasTriple
  refine ⟨0, 1, 2, ?_, ?_⟩
  · refine ⟨[], [], ?_⟩
    simp [colliderTrail02, Trail.toList]
  · right
    constructor
    · change
        (0, 1) ∈ ({(0, 1), (2, 1)} : Finset (ℕ × ℕ)) ∧
          (2, 1) ∈ ({(0, 1), (2, 1)} : Finset (ℕ × ℕ))
      simp
    · simp

end DAGExamples

/--
The unrestricted statement `DAG.dSeparated G X Y Z → dSeparates G X Y Z` is
false for the current public definitions.  If an endpoint is conditioned on,
`DAG.dSeparationGraph` deletes that endpoint, while the trail predicate still
allows the one-edge trail with no internal triple.
-/
theorem dsep_complete_endpoint_in_Z_counterexample :
    ∃ (G : DAG) (X Y Z : Finset ℕ),
      DAG.dSeparated G X Y Z ∧ ¬ dSeparates G X Y Z := by
  classical
  refine ⟨DAGExamples.chain3, ({0} : Finset ℕ), ({1} : Finset ℕ), ({0} : Finset ℕ),
    ?_, ?_⟩
  · intro x hx y hy hreach
    simp only [Finset.mem_singleton] at hx hy
    subst x
    subst y
    rcases hreach with ⟨p⟩
    cases p with
    | cons h _ =>
        have h0_not_mem :
            0 ∉ DAGExamples.chain3.dSeparationGraphNodes ({0} : Finset ℕ)
              ({1} : Finset ℕ) ({0} : Finset ℕ) := by
          simp [DAG.dSeparationGraphNodes]
        exact h0_not_mem h.1
  · intro hsep
    have hblocked :
        (Trail.forward (G := DAGExamples.chain3) (u := 0) (w := 1) (v := 1)
          (by
            change (0, 1) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ))
            simp)
          (Trail.nil 1)).isBlocked ({0} : Finset ℕ) :=
      hsep 0 (by simp) 1 (by simp)
        (Trail.forward (G := DAGExamples.chain3) (u := 0) (w := 1) (v := 1)
          (by
            change (0, 1) ∈ ({(0, 1), (1, 2)} : Finset (ℕ × ℕ))
            simp)
          (Trail.nil 1))
    rcases hblocked with ⟨a, b, c, htriple, _⟩
    rcases htriple with ⟨pre, post, hlist⟩
    have hlen := congrArg List.length hlist
    simp [Trail.toList] at hlen
    omega

theorem not_forall_dsep_complete :
    ¬ ∀ (G : DAG) (X Y Z : Finset ℕ), DAG.dSeparated G X Y Z → dSeparates G X Y Z := by
  intro h
  rcases dsep_complete_endpoint_in_Z_counterexample with ⟨G, X, Y, Z, hdsep, hnot⟩
  exact hnot (h G X Y Z hdsep)

theorem not_forall_dsep_iff :
    ¬ ∀ (G : DAG) (X Y Z : Finset ℕ), dSeparates G X Y Z ↔ DAG.dSeparated G X Y Z := by
  intro h
  rcases dsep_complete_endpoint_in_Z_counterexample with ⟨G, X, Y, Z, hdsep, hnot⟩
  exact hnot ((h G X Y Z).mpr hdsep)

end

end FiniteQuerySandbox
